name: Build Apk

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          flutter build apk --release \
          --target-platform android-arm64 \
          --split-per-abi \
          --obfuscate \
          --split-debug-info=./build/debug-info

      - name: Generate release timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d_%H%M%S')"

      - name: Upload to GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-arm64-v8a-release.apk"
          tag: v${{ steps.timestamp.outputs.timestamp }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true